### ISSUE TITLE
Have separate compute entities

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#1]
We need to have the ability to deploy NSX to separate compute entities:
1. Multiple clusters in the compute manager- In many cases customers will have multiple clusters where they will need to deploy NSX to. Example
![multi compute feature](https://user-images.githubusercontent.com/38479071/43167794-ee5719e6-8f68-11e8-8b85-adddbcd1caf0.jpg)
 multi AZ for PAS and PKS. for this purpose we will need to be able to support multiple clusters configured in a compute managers (Or in multiple compute managers but more likely in a single one)    
2. Separate vCenters - In some cases customers will have separate vCenters for management and compute. We need to be able to specify multiple compute managers where NSX will be installed automatically (This is not in high priority but may be easy to do with the multi cluster capability)
3. Individual ESXi hosts - in cases where a customer is deploying the management cluster or any other cluster spread across L3 boundaries (multiple racks) we will need to allow the addition of individual ESXi hosts to install NSX on with different uplink profile 
4. Multiple uplink profile - for point 3 above, and for places where there are different northbound network configurations for ESXi hosts (such as VLAN IDs) we need to be able to specify an uplink profile that is different

**Comment by kais66** [comment]
This has been addressed.
