### ISSUE TITLE
Need to remove edge cluster assignments from T1

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#10]
No T1 should have Edge cluster configured except T1-PAS-ERT which runs the LB
Having Edge cluster configured forces sub-optimal routing through the edge

**Comment by kais66** [comment]
fixed. This is the sample T1 router config with edge cluster specified:
  - name: T1-Router-PAS-ERT
    switches:
    - name: PAS-ERT
      logical_switch_gw: 192.168.24.1
      subnet_mask: 24
    edge_cluster: true

if edge_cluster key is missing, the T1 router will not be linked with an edge cluster.
