### ISSUE TITLE
Uplink logical switch vlan

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#11]
The uplink logical switch "uplink-vlan-ls" was configured with a VLAN.
But couldn't find a parameter to set it.
We should set it to 0 always and allow an advanced config in the future

**Comment by kais66** [comment]
The vlan in this case has been set to 0. It's currently a hidden param, along with the uplink port IP and subnet. We can allow them as secondary config params. Currently they are hidden and we only exposed the absolutely essential ones.
