### ISSUE TITLE
SNAT Pools have not been created

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#14]
SNAT Pools were not created.
these are the required params:

nsx_t_external_ip_pool_spec: |
  external_ip_pools:
  - name: snat-vip-pool-for-pas
    cidr: 10.208.40.0/24
    start: 10.208.40.10 # Should not include gateway
    end: 10.208.40.200  # Should not include gateway

  - name: snat-vip-pool-for-pks
    cidr: 10.208.50.0/24
    start: 10.208.50.10 # Should not include gateway
    end: 10.208.50.200  # Should not include gateway

**Comment by kais66** [comment]
fixed
