### ISSUE TITLE
IP block not being created

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#16]
IP Blocks not being created 

here are the required params:

nsx_t_container_ip_block_spec: |
  container_ip_blocks:
  - name: PAS-container-ip-block
    cidr: 10.4.0.0/16
  - name: PKS-node-container-ip-block
    cidr: 11.4.0.0/16
  - name: PKS-pod-container-ip-block
    cidr: 12.4.0.0/16

**Comment by kais66** [comment]
this has been fixed
