### ISSUE TITLE
Add Uplink ports and static route

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#17]
nsx_t_t0router_spec: |
   t0_router:
     name: DefaultT0Router
     ha_mode: 'ACTIVE_STANDBY'
     Specify the edges to be used for hosting the T0Router instance
    edge_indexes:
 Index starts from 1 -> denoting nsx-t-edge-01
       primary: 1   # Index for primary edge to be used
       secondary: 2 # Index for secondary edge to be used
     vip: 10.13.12.103/27
     ip1: 10.13.12.101/27
     ip2: 10.13.12.102/27
     vlan_uplink: 0
     static_route:
       next_hop: 10.13.12.1
       network: 0.0.0.0/0
       admin_distance: 1

**Comment by kais66** [comment]
addressed
