### ISSUE TITLE
Auto install of NSX in cluster

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#2]
Need to enable the capability to auto-install nsx-t and creation of TNs when a server is added to a cluster in the compute manager
![image](https://user-images.githubusercontent.com/38479071/43167888-508daa80-8f69-11e8-927c-61b1425f33ef.png)
![image](https://user-images.githubusercontent.com/38479071/43167955-74459384-8f69-11e8-86d1-8a317421ebae.png)

**Comment by kais66** [comment]
created an issue in the ansible repo as related module is missing there

**Comment by goehmen** [comment]
ansible repo as related module - this has been completed on the ansible side.

**Comment by kais66** [comment]
Auto installation has been addressed. The need for distinct uplink profiles is tracked at https://github.com/kais66/nsx-t-gen/issues/1
