### ISSUE TITLE
need to add check for Edge node deployment

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#20]
My pipeline failed because I did not have enough memory in my hosts to power on the edge.
I fixed the problem and restarted the pipeline, it just skipped that task and turned green while the edge was still down and not working.
Need to check that the edge is on and registered before moving on, same for controllers

**Comment by kais66** [comment]
added parameter resource_reservation_off and the check for connections to controllers and edge nodes.
