### ISSUE TITLE
Sample cluster auto install parameter

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#23]
- display_name: "{{host_uplink_prof}}"
  description: "Host Overlay Profile"
  teaming:
    active_list:
    - uplink_name: "uplink-1"
      uplink_type: PNIC
    standby_list:
    - uplink_name: "uplink-2"
      uplink_type: PNIC
    policy: FAILOVER_ORDER
  transport_vlan: "21"

We are missing the assignment of the uplinks to physical NICs

**Comment by kais66** [comment]
Auto-install of multi-clusters has taken this sample config into account.
