### ISSUE TITLE
Load balancer is not being created

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#24]
VIP are created but LB is not.
This is the error in the pipeline

{u'error_code': 23500, u'related_errors': [{u'error_code': 23721, u'error_message': u'The logical router LogicalRouter/071c4339-808e-450c-a3ac-1ebad1cc74db does not have associated edge cluster to deploy a load balancer service LoadBalancerService/fec19889-a804-424b-b92b-11bb7cb1d9da.', u'httpStatus': u'BAD_REQUEST', u'module_name': u'LOAD-BALANCER'}], u'error_message': u'Found errors in the request. Please refer to the relatedErrors for details.', u'httpStatus': u'BAD_REQUEST', u'module_name': u'LOAD-BALANCER'}
NSX Mgr updated to use newly generated CSR!!
    Update response code:202

This is the config

  - name: PAS-ERT-LBR
    t1_router: T1-Router-PAS-ERT # Should match a previously declared T1 Router
    size: small                  # Allowed sizes: small, medium, large

T1 router T1-Router-PAS-ERT does have an edge cluster in teh param

 - name: T1-Router-PAS-ERT
    switches:
    - name: PAS-ERT
      logical_switch_gw: 192.168.20.1 # Last octet should be 1 rather than 0
      subnet_mask: 24
      edge_cluster: true

But its not getting assigned in NSX

![image](https://user-images.githubusercontent.com/38479071/44319829-480a5680-a40c-11e8-9144-97e23036408f.png)

**Comment by kais66** [comment]
The `edge_cluster` key should be aligned with `switches`, like:

```diff
  - name: T1-Router-PAS-ERT
    switches:
    - name: PAS-ERT
      logical_switch_gw: 192.168.20.1 # Last octet should be 1 rather than 0
      subnet_mask: 24
-     edge_cluster: true
+   edge_cluster: true
```
