### ISSUE TITLE
Need to move away from MOIDs

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#3]
The current state of the param file requires specifying clusters, network and storage for the controllers using their MOID due to requirements by the NSX-Manager auto deploy feature. . 
controller_compute_id: "domain-c26"
controller_storage_id: "datastore-817"
controller_management_network_id: "dvportgroup-42 "

This is very cumbersome and lengthy. Perhaps there's a way to bypass? if not we should input the names of the objects in the param file and convert to the MOID automatically. 

here is a nice article from William lam 
https://www.virtuallyghetto.com/2011/11/vsphere-moref-managed-object-reference.html
and another external one
https://www.danilochiavari.com/2014/03/28/how-to-quickly-match-a-moref-id-to-a-name-in-vmware-vsphere/

**Comment by kais66** [comment]
Niran I think this is something that's very valuable. 
I gave a shot to the perl script. It has multiple dependencies including vSphere perl SDK which we probably cannot package in the docker container. I will try to find a way to get the mapping between moRefID and names ourselves.

**Comment by kais66** [comment]
fixed
